site_name: FICO

theme:
  name: material
  language: pt-BR

nav:
  - Home: index.md
  - tutorials.md
  - Utilização do módulo CPI - Jupyter Notbook: tutorials/tutorial_cpi.ipynb
  - reference.md
  - explanation.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            separate_signature: yes
            show_source: yes
            show_root_full_path: no
  - search
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
